server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8

spring:
  messages:
    basename: i18n.messages
  profiles:
    active: @env@
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  type-aliases-package: com.wdcloud.model
  mapper-locations: classpath:mapper/**/*.xml

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

management:
  endpoints:
    web:
      exposure:
        include: "*"